#!/usr/bin/env bash

if [[ $DOCKER_CONTAINER -ne 1 ]]; then
    if [[ $(docker-compose ps -q | wc -l) -gt 0 ]]; then
        source bin/helpers/docker
        runOnDocker ruby
    fi
fi

echo "Starting unit tests"
bundle exec rake spec
if [ $? -ne 0 ]; then
    echo ""
    echo ""
    echo "Unit tests failed; push aborted!"
    exit 1
fi

echo
echo "Starting rubocop"
bundle exec rubocop --format worst --format simple --format offenses
if [ $? -ne 0 ]; then
    echo ""
    echo ""
    echo "Rubocop failed; push aborted!"
    exit 1
fi

echo
echo "All pre-push checks passed! Pushing to remote"
