inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - 'lib/**/*.rb'
    - 'test/**/*.rb'
  Exclude:
    - 'bin/**/*'



Style/RedundantSelf:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/IndentationConsistency:
  EnforcedStyle: rails

Metrics/LineLength:
  Max: 120

Style/ClassVars:
  Exclude:
    - 'lib/slayer/service.rb'

Style/MutableConstant:
  Exclude:
    - 'lib/slayer/version.rb'
