AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.1
  Include:
    - 'lib/**/*.rb'
    - 'test/**/*.rb'
    - 'spec/**/*.rb'
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
    - 'bin/**/*'
    - 'test/fixtures/**/*.rb'

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Style/Documentation:
  Enabled: false

Naming/BlockForwarding:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/CommentIndentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 120

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Naming/MethodParameterName:
  AllowedNames:
    - _

Style/ClassVars:
  Exclude:
    - 'lib/slayer/service.rb'

Style/MutableConstant:
  Exclude:
    - 'lib/slayer/version.rb'
