inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.1
  Include:
    - 'lib/**/*.rb'
    - 'test/**/*.rb'
  Exclude:
    - 'bin/**/*'
    - 'test/fixtures/**/*.rb'


Style/RedundantSelf:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/CommentIndentation:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: rails

Metrics/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 120

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - _

# Temporarily disabled until this can be resolved in the todo file
# Style/Documentation:
#   Exclude:
#     - 'spec/**/*'
#     - 'test/**/*'
#     - 'lib/ext/**/*'

Style/ClassVars:
  Exclude:
    - 'lib/slayer/service.rb'

Style/MutableConstant:
  Exclude:
    - 'lib/slayer/version.rb'
